### PR TITLE
Fix/kc use time bool

### LINKED ISSUE #50: Setting `TAB_USE_TIME_FOR_BUILD_NUMBER` to `FALSE` does not disable it
When having this feature turned on for some environments like so:
`TAB_USE_TIME_FOR_BUILD_NUMBER=TRUE`

Temporarily disabling it using:
`TAB_USE_TIME_FOR_BUILD_NUMBER=FALSE`
... does not work.
The only way to disable it is to delete the line that defines the variable.

### PR DESCRIPTION
**Pull request by KaneCheshire**
Fixes #50

### CODE REVIEW

**Review by zborrell-ford — DISMISSED** [review]

File: setup.sh [hunk 1]
```diff
@@ -20,7 +20,7 @@ GYM_CODE_SIGNING_IDENTITY="" #Code Sign Identitify
 FL_HOCKEY_TEAMS="" #Hockey ID (number not name)
 FL_HOCKEY_NOTIFY= #Email team when new build avialable? 0 = No, 1 = Yes
 ICON_OVERLAY_ASSETS_BUNDLE="" #Path to .xcassets
-TAB_USE_TIME_FOR_BUILD_NUMBER= #Use Time and date for build number or BUILD_NUMBER environment variable (created by jenkis or team city) true = use time, false = use BUILD_NUMBER
+TAB_USE_TIME_FOR_BUILD_NUMBER=true #Use Time and date for build number or BUILD_NUMBER environment variable (created by jenkis or team city) true = use time, false = use BUILD_NUMBER
```
Comment (yliu342) [inline setup.sh:23]: Do we want to use date+time for build number by default when setup?

File: Fastfile [hunk 2]
```diff
@@ -92,7 +92,7 @@ def _build_and_deploy_to_hockey
 end
 
 def _build_number
-  use_timestamp = ENV['TAB_USE_TIME_FOR_BUILD_NUMBER'] || false
+  use_timestamp = ENV['TAB_USE_TIME_FOR_BUILD_NUMBER'].to_s == 'true' || false
```
Comment (nkirev-ford) [inline Fastfile]: Would this work in the scenario where the value is `'TRUE'`?
Is that a valid scenario? 
If it is, maybe we could lowercase the value just in case before evaluating the expression.

File: setup.sh (hunk 1 above)
Comment (KaneCheshire) [reply setup.sh:23]: I personally think its the most sensible thing since it ensures build numbers are always greater every build, regardless of where it's being sent to

File: Fastfile (hunk 2 above)
Comment (KaneCheshire) [reply Fastfile]: I guess it is! Easy to add

Comment (KaneCheshire) [reply Fastfile]: Updated

File: setup.sh (hunk 1 above)
Comment (yliu342) [reply setup.sh:23]: that's true

**Review by yliu342 — APPROVED** [review]

**Review by nkirev-ford — APPROVED** [review]
